### ISSUE TITLE
Webpack is causing issues when compiling due to images in assets folder not found

### ISSUE THREAD

**Issue by Simbaclaws** [justintadlock/first-draft#3]
Hi there,

Currently I'm trying to use your first draft theme to build a block theme. However when I try to add images in my scss files and compile them using webpack, I'm getting error messages saying:

```HookWebpackError: Cannot find module '/wp-content/themes/my-theme/assets/images/background.png'```
This is because I am putting those url's in my css for loading images from my assets folder.

So in my scss file I have somewhere where it says:
background-img: '/wp-content/themes/my-theme/assets/images/background.png';

However webpack obviously doesn't know that URL and therefore is creating compilation errors.

How should I go about this? What is the recommended way for adding files in this theme for webpack to support this kind of configuration?

Please let me know how I should fix my build process...

**Comment by justintadlock** [comment]
What's your webpack configuration?

If you use something like the `@wordpress/scripts` package, it includes an image loader: https://developer.wordpress.org/block-editor/reference-guides/packages/packages-scripts/#using-fonts-and-images

**Comment by Simbaclaws** [comment]
hmmm odd, I am using the @wordpress/scripts package, perhaps something is wrong with the way I set it up. When referencing files even if I use ../../assets/images/background.jpg for example it doesnt' want to compile.

I'll have a look tomorrow and I'll let you know what I might've done wrong.

**Comment by justintadlock** [comment]
Just closing this because it's unrelated to the theme, but feel free to continue discussing here.

**Comment by Simbaclaws** [comment]
I'm not quite sure how I fixed it, but I think I used the following webpack.config.js:

```javascript
// Import the original config from the @wordpress/scripts package.
const defaultConfig = require("@wordpress/scripts/config/webpack.config");

// Import the helper to find and generate the entry points in the src directory
const {getWebpackEntryPoints} = require("@wordpress/scripts/utils/config");

// Add any a new entry point by extending the webpack config.
module.exports = {
	...defaultConfig,
	entry: {
		...getWebpackEntryPoints(),
	}
}
```
and a package.json like this:
```json
{
	"name": "theme-name",
	"version": "1.0.0",
	"description": "A theme for a website I'm working on",
	"main": "index.js",
	"scripts": {
		"test": "echo \"Error: no test specified\" && exit 1",
		"start": "wp-scripts start --webpack-src-dir=blocks",
		"build": "wp-scripts build --webpack-src-dir=blocks",
		"develop": "npm-run-all --parallel start sync",
		"sync": "browser-sync start --proxy 'mywebsite.local' --files 'build/*'",
		"format": "wp-scripts format",
		"lint:css": "wp-scripts lint-style",
		"lint:js": "wp-scripts lint-js",
		"lint:md:docs": "wp-scripts lint-md-docs",
		"lint:pkg-json": "wp-scripts lint-pkg-json"
	},
	"author": "",
	"license": "GPL-2.0-or-later",
	"devDependencies": {
		"@wordpress/scripts": "^26.8.0",
		"browser-sync": "^2.29.3",
		"glob": "^10.3.3",
		"npm-run-all": "^4.1.5"
	}
}
```

Everything is working now when referencing files for some reason. I have no idea what I was doing wrong.

I'm sorry for creating an issue in your repository...

I also have some questions regarding the theme.json file in general but I'll try to figure that out myself first.

Currently I have a extra "area" called sidebar, that I need for a custom sidebar that is a part of specific templates. But I want to be able to set the spacing for that specific area and I'm not sure whether the theme.json  is the place to do that since it is a part of an area, or whether that should be a part of the sidebar template part.

I'm also trying to figure out how I should do my css changes in the theme, I want to move to more block based css changes, but I tend to override a few things for my theme globally through an enqueued frontend script.

**Comment by justintadlock** [comment]
No problem with filing the issue here and thanks for posting your experience.

I've been doing some experimenting on my own with `@wordpress/scripts` in a separate theme and think I want to eventually bring it over to this. Either that or create a separate "advanced" boilerplate/starter.

**Comment by justintadlock** [comment]
Also, feel free to borrow from my `webpack.config.js` here: https://github.com/x3p0-dev/x3p0-ideas/blob/master/webpack.config.js

I haven't tested it with images (other than a custom copy implementation to the build folder).
